Repository red-hat-storage/odf-multicluster-orchestrator, pull requests merged in 2021-08, with the labels that each got.

#15 run integration test in vendor mod in OpenShift CI
  Makefile
Labels: approved

#8 Add token exchange addon to orchestrator
  Dockerfile
  Makefile
  addons/token-exchange/manifests/hub_clusterrole.yaml
  addons/token-exchange/manifests/hub_clusterrolebinding.yaml
  addons/token-exchange/manifests/hub_role.yaml
  addons/token-exchange/manifests/hub_rolebinding.yaml
  addons/token-exchange/manifests/spoke_clusterrole.yaml
  addons/token-exchange/manifests/spoke_clusterrolebinding.yaml
  addons/token-exchange/manifests/spoke_deployment.yaml
  addons/token-exchange/manifests/spoke_role.yaml
  addons/token-exchange/manifests/spoke_rolebinding.yaml
  addons/token-exchange/manifests/spoke_serviceaccount.yaml
  addons/token-exchange/token_exchanger_addon.go
  addons/token-exchange/token_exchanger_agent.go
  bundle/manifests/odf-multicluster-orchestrator.clusterserviceversion.yaml
  cmd/manager.go
  cmd/root.go
  cmd/token_exchanger_agent.go
  config/manager/manager.yaml
  config/rbac/role.yaml
  controllers/manager.go
  controllers/mirrorpeer_controller.go
  go.mod
  go.sum
  main.go
Labels: approved

#24 add gh action to publish images on push to master
  .github/workflows/publish-images.yaml
Labels: approved

#25 fix manager scheme & use it for testing reconciler
  controllers/manager.go
  controllers/mirrorpeer_controller_test.go
Labels: approved

#26 Add clusterrole and clusterrolebinding permissions to orchestrator
  bundle/manifests/odf-multicluster-orchestrator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/mirrorpeer_controller.go
Labels: approved

#30 increase memory resource for the operator
  bundle/manifests/odf-multicluster-orchestrator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, lgtm

#17 Add MirrorPeerSecret controller
  bundle/manifests/odf-multicluster-orchestrator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/common-controller-utils.go
  controllers/common/secret-utils.go
  controllers/manager.go
  controllers/mirrorpeer_controller.go
  controllers/mirrorpeersecret_controller.go
  controllers/named-peerref-with-data.go
Labels: approved, lgtm

#20 sync green secrets from hub to managed clusters
  addons/token-exchange/green_secret_controller.go
  addons/token-exchange/green_secret_controller_test.go
  addons/token-exchange/token_exchanger_agent.go
  go.mod
Labels: approved, lgtm

#23 MirrorPeer status conditions
  api/v1alpha1/mirrorpeer_types.go
  bundle/manifests/multicluster.odf.openshift.io_mirrorpeers.yaml
  config/crd/bases/multicluster.odf.openshift.io_mirrorpeers.yaml
  controllers/common/predicate.go
  controllers/mirrorpeer_controller.go
Labels: approved, needs-ok-to-test, lgtm

#32 fix data stored in the secret copied from hub to managed cluster
  addons/token-exchange/green_secret_controller.go
  addons/token-exchange/green_secret_controller_test.go
Labels: approved, lgtm

#31 update golang dependency
  go.mod
  go.sum
Labels: approved

#33 add secret name to storagecluster CR in the managed cluster
  addons/token-exchange/green_secret_controller.go
  addons/token-exchange/green_secret_controller_test.go
  addons/token-exchange/manifests/spoke_clusterrole.yaml
  addons/token-exchange/token_exchanger_agent.go
  go.mod
  go.sum
Labels: approved, lgtm
