Repository red-hat-storage/odf-multicluster-orchestrator, pull requests merged in 2024-09, with the labels that each got.

#232 Bug 2299671: [release-4.16] update vault version
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test, bugzilla/valid-bug, bugzilla/severity-medium

#234 change operator capability to "Seamless Upgrades" in CSV
  bundle.Dockerfile
  bundle/manifests/odf-multicluster-orchestrator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manifests/bases/odf-multicluster-orchestrator.clusterserviceversion.yaml
Labels: approved, lgtm

#230 Bug 2302463: console: use github.com/openshift/api/console/v1
  console/console.go
  console/console_test.go
  controllers/manager.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high
